

#Given a array tell the maximum sum generated by the subarrays 
#we use Kadanes algorithm


class Max_sum:
  def __init__(self,arr):
    self.arr=arr
    self.csum=[self.arr[0]]
    self.max_sum=[self.arr[0]]
  
  
  def calculate_sum(self):
    for i in range(1,len(self.arr)):
      l=max(self.arr[i],(self.arr[i]+self.csum[i-1]))
      self.csum.append(l)
      if l>self.max_sum[i-1]:
        self.max_sum.append(l)
      else:
        self.max_sum.append(self.max_sum[i-1])
    return self.max_sum[len(self.arr)-1]    


#test case 1
max_sum=Max_sum([2,-1,3,-4,5,-3])
max_val=max_sum.calculate_sum()
print(max_val)
#test case 2
max_sum=Max_sum([2,-1,4,2,-3])
max_val=max_sum.calculate_sum()
print(max_val)




